### ISSUE TITLE
AWS IAM 계정 생성 후 공유

### ISSUE THREAD

**Issue by anjiwon319** [kookmin-sw/capstone-2024-08#37]
## AWS IAM 사용자 Admin 그룹 생성 후 추가
FastAPI와 AWS EC2를 활용해 백엔드 서버를 구축할 필요를 느껴 IAM 권한을 생성하여 공유하고자 합니다.
Admin 권한으로 원하는 작업에 모두 접근 가능하게끔 구성한 사용자 그룹에 추가했습니다.

메일로 해당 IAM 권한을 위한 인증 정보를 메일로 전송하였으니 확인 부탁드리고 댓글 부탁드립니다.

<br>

### AWS 접근 권한 요청한 팀원 목록

- [X] #38

**Comment by anjiwon319** [comment]
## IAM 사용자 권한으로 AWS 접근
권한을 받고 나면 IAM에 들어가서 자신의 access key를 발급하여 해당 키로 접근하면 됩니다.
<img width="397" alt="image" src="https://github.com/kookmin-sw/capstone-2024-08/assets/66212424/887cc568-fff0-44b7-9f62-a84c01a5df95">

<br>
<br>

**Comment by anjiwon319** [comment]
# How to Connect AWS CLI
발급한 키로 로컬 컴퓨터에서 AWS에 접근해 정보를 가져오고 필요한 작업들을 수행하려면 로컬 컴퓨터에서 AWS CLI 설정을 해줘야합니다.
아래 AWS CLI 설치 및 Configure 방법을 정리해두었으니 참고하시길 바랍니다.

<br>

## Install AWS CLI

---

```bash
$ sudo apt-get install awscli   # Ubuntu/Debian
$ brew install awscli           # macOS
```

위 명령어로 AWS CLI를 설치한다.

설치가 꽤 오래걸렸는데 설치 과정에서 이미 기존에 존재하는 라이브러리들도 업그레이드 하는 모습을 확인할 수 있다.

## Configure AWS

---

설치가 끝났으면 이제 **`aws configure`** 명령을 사용하여 AWS 자격 증명을 설정할 차례이다.

```bash
$ aws configure
AWS Access Key ID [None]: <YourAccessKeyId>
AWS Secret Access Key [None]: <YourSecretAccessKey>
Default region name [None]: <YourRegionName>
Default output format [None]: json
```

잘 되었는지 테스트하고자  aws s3 ls  명령을 사용하여 S3 버킷 목록을 가져오는 AWS CLI 명령을 실행해보면 잘 가져오는 걸 확인할 수 있다.
우리의 경우 아직 S3 버킷이 없기 때문에 아무것도 없는 게 맞다.

**Comment by why-arong** [comment]
확인했으니 이슈 닫을게요
