### ISSUE TITLE
Bug: Merge 이후 .env 파일을 찾을 수 없어 flutter run 실행 불가능 

### ISSUE THREAD

**Issue by anjiwon319** [kookmin-sw/capstone-2024-08#39]
## 문제 상황
4/19 코드 병합 이후 flutter 프로젝트를 실행했을 때 `.env`의 파일을 찾을 수 없다며 실행되지 않는 문제가 발생했습니다.

<img width="880" alt="image" src="https://github.com/kookmin-sw/capstone-2024-08/assets/66212424/0db5b9ab-c028-4e0a-9fbd-2118a1399889">

<br>

[`pubspec.yaml` 파일에서 `.env` 파일의 경로를 재설정 해줬는데도 ](https://github.com/anjiwon319/capstone-2024-08/commit/5cbdf8002c8341e6bd4a4f647b3aea5ada4603df)여전히 위와 같은 에러가 발생합니다.

<br>
<br>

## TO-DO
현재 `mater` 브랜치에 올라가있는 코드 기준으로 다른 팀원들의 로컬 환경에서는 원활하게 실행되는 지 확인이 필요합니다.

**Comment by anjiwon319** [comment]
@YunHaaaa @Shin-MG  확인 해주시고 알려주시면 감사하겠습니도!

**Comment by Shin-MG** [comment]
저는 잘 동작합니다.

**Comment by anjiwon319** [comment]
ㅜㅜ저는 왜 안될까요.. assets/config/.env 해당 파일 참고하는 거 맞죠??

**Comment by Shin-MG** [comment]
제가 4월 5일에 올린 커밋 보시면, .env 경로를 수정했습니다. 로컬에서 .env 파일 위치 옮기고, main.dart랑 pubspec.yaml도 그 경로에 맞추어 수정해 올렸습니다. 그런데, 한참 전에 merge가 진행됐던 부분이라서 그 이후에 개발 진행하시는 동안 문제가 없었던 것 같아 이게 해결책이 아닐 수도 있을 거 같네요. 확인해보시고 코멘트 주세요!

**Comment by anjiwon319** [comment]
참고해봤는데도 여전히 `.env` 파일을 찾지 못하는 문제가 발생합니다ㅜㅜ 현재 .`env` 파일의 위치가 `front/assets/config/.env `맞나요?
`config` 폴더 바깥으로 이동시켜도 여전히 동작하지 않습니다..!

**Comment by Shin-MG** [comment]
파일 위치 front/.env입니다.

**Comment by anjiwon319** [comment]
아놔 역시 바꿔서 다시 해보겠습니다.....

**Comment by anjiwon319** [comment]
마법처럶 해결.........................감사해여 민경쒸
근데 요상한 일이네 .env 파일이 gitignore에 들어가있어서 파일 위치 변경이 반영 안된 것 같은데 하은이는 어떻게 된 걸까여
