### ISSUE TITLE
Elastic ip 사용 여부 + EBS 볼륨 설정

### ISSUE THREAD

**Issue by why-arong** [kookmin-sw/capstone-2024-08#43]
## 문제 상황
현재 비용문제 때문에 ec2 인스턴스를 쓸 때마다 **껐다 켰다**를 반복하고 있는데요.
이러면 재실행 시킬 때마다 **인스턴스의 ip주소가 바뀌는 문제**가 생겨요

(예시. ip: 1.1.1.1 -> 다시 켰을 때 ip: 2. 2. 2. 2)

그러면 플러터가 api를 이용할 때, 지정한 api endpoint를 계속 바꿔줘야 하는 문제가 생깁니다. 

```dart
import 'package:http/http.dart' as http;
import 'dart:convert';

Future<void> fetchServerData() async {
  // 서버의 API 엔드포인트 주소
  const String serverAddress = 'http:// amazon ~~~~ {public ip} ~~~~~~~~~'; <- 이거 바뀜 
  try {
    // GET 요청 보내기
    final response = await http.get(Uri.parse(serverAddress));
```
그래서!!

elastic ip(**고정 ip**)를 사용하면 해결이 되는데!

문제는 이게 인스턴스당 하나는 무료로 붙여주거든요? 근데 이게 또 계속 인스턴스가 실행된다는 가정 하에 무료고
만약 저희처럼 중지를 시켜버리면 중지되어 있는 시간동안 돈이 들어요.. 
기껏 무료로 만든 ip를 쓰지 않을거면 돈내놓으라는 거죠

- **실행 중인 인스턴스와 연결되지 않은 각 탄력적 IP 주소에 대해 시간당 0.005 USD(비례 할당으로 계산**) 

## 해결 방법
그래서 해결 방법은 
1. 걍 elastic ip 돈 내기 (한달 동안 인스턴스가 꺼져있다는 가정하에 5천원 정도)
2. 불편하지만 그냥 동적 ip 사용하고 항상 확인하면서 코드를 고치기
3. ec2 서버를 끄지 말기(얘는 1번보다 더 많이 듦)

어캐함

**Comment by anjiwon319** [comment]
Elastic IP 사용합시다 !

**Comment by anjiwon319** [comment]
## EC2 Instance Elastic IPs 연결

이전에 생성해뒀던 백엔드 인스턴스에 Elastic IP 연결해뒀습니다!
EC2 페이지 들어가셔서 해당 IP 주소 확인하시고 사용하시면 됩니다 :)

<img width="306" alt="image" src="https://github.com/kookmin-sw/capstone-2024-08/assets/66212424/80fca463-6dc1-49d2-8c4c-5ca83acc184d">

**Comment by anjiwon319** [comment]
## EBS 볼륨 설정

[[AWS] EC2에 EBS 추가하는 방법 (https://jenakim47.tistory.com/68)](https://jenakim47.tistory.com/68)

기존 인스턴스에 `/dev/sdd`로 EBS 추가해뒀으니까 이후 마운트 작업이 필요합니다!

위 참고 링크에서 3번 부터 확인하면서 따라하면 됩니다
