### ISSUE TITLE
Instance 정하기

### ISSUE THREAD

**Issue by why-arong** [kookmin-sw/capstone-2024-08#47]
https://aws.amazon.com/ec2/pricing/on-demand/

Instance name | On-Demand hourly rate | vCPU | Memory | Storage | Network performance
-- | -- | -- | -- | -- | --
inf1.xlarge | $0.228 | 4 | 8 GiB | EBS Only | Up to 25 Gigabit
inf1.2xlarge | $0.362 | 8 | 16 GiB | EBS Only | Up to 25 Gigabit
g4ad.xlarge | $0.37853 | 4 | 16 GiB | 150 GB NVMe SSD | Up to 10 Gigabit
g4dn.xlarge | $0.526 | 4 | 16 GiB | 125 GB NVMe SSD | Up to 25 Gigabit

gpu 장착된 인스턴스 (가격 순 정렬)

**Comment by why-arong** [comment]
pc방 보다는 쌈 ^~^

**Comment by why-arong** [comment]
inf는 nvidia 칩이 아니여서 우리 목적에 맞지 않고
그 밑에
g4ad.xlarge 는 서울에서는 사용 못함(제일 가까운 리전은 일본)
g4dn.xlarge 부터 서울에서 사용 가능

**Comment by anjiwon319** [comment]
#53
